### ISSUE TITLE
Heroku-OTP 25.1 and 25.1.1 builds failing

### ISSUE THREAD

**Issue by ethangreenberg** [elixir-buildpack/heroku-otp#10]
Hi all!

It looks like the workflows for `Build New OTP Release` are failing for Erlang 25.1 and 25.1.1. As a result, I'm not able to use Erlang 25.1 or 25.1.1 in my heroku releases.
<img width="943" alt="Screen Shot 2022-10-04 at 12 23 12 PM" src="https://user-images.githubusercontent.com/15315492/193909833-6e696a44-b756-4754-a466-814e3669e954.png">
<img width="1049" alt="Screen Shot 2022-10-04 at 12 25 01 PM" src="https://user-images.githubusercontent.com/15315492/193909849-16e3fd8a-a1c4-4dec-9673-4e78e7d0183d.png">

**Comment by matt-glover** [comment]
This build failure appears to be failing during a heroku-16 stack build which has been EOL for a while: https://help.heroku.com/0S5P41DC/heroku-16-end-of-life-faq

And recently the postgres team dropped xenial from their apt repo <https://wiki.postgresql.org/wiki/Apt#News>:
> 2022-09-19: Ubuntu xenial and impish have been removed from apt.postgresql.org.

Maybe this repo should drop support for that stack going forward?

**Comment by KazW** [comment]
This should be fixed, the builds for the affected versions should be available in the next 15-30 minutes once the build jobs have completed. Thanks for opening the issue, cheers! 🍻

Affected versions:
* 23.3.4.18
* 25.1
* 25.1.1
