### ISSUE TITLE
Sync OTP Releases not updating due to scheduled workflow is disabled

### ISSUE THREAD

**Issue by tskogberg** [elixir-buildpack/heroku-otp#19]
![Skärmavbild 2024-02-20 kl  17 42 42](https://github.com/elixir-buildpack/heroku-otp/assets/1674100/67e93c34-916b-4d0f-992f-1a1c863bfc25)

Source path: https://github.com/elixir-buildpack/heroku-otp/actions/workflows/release-sync.yml

Resulting in no new OTP releases.

**Comment by KazW** [comment]
Thanks for letting me know. I've re-enabled this.

**Comment by KazW** [comment]
The new builds have been kicked off.

**Comment by tskogberg** [comment]
Thank you!
